version: "3.7"
services:
    app:
        build:
            args:
                user: 1000
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: carolnabel
        container_name: carolnabel-app    
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./devops/app/php.ini:/usr/local/etc/php/php.ini
        networks:
            - carolnabel

    db:
        image: mysql:8
        container_name: carolnabel-db        
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}            
        networks:
            - carolnabel

    nginx:
        image: nginx:alpine
        container_name: carolnabel-nginx        
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./devops/nginx:/etc/nginx/conf.d/
        networks:
            - carolnabel

networks:
    carolnabel:
        driver: bridge